✨feat : Arounder Detail Contents Writer/Viewer
codestates-seb/seb40_main_001 pull request #103
Opened 2022-11-22 07:28 UTC by nada1221

✨feat : Arounder Detail Contents Writer/Viewer

2022-11-22 07:31 UTC, nada1221 commented
ApplicantSet 의 경우 writer 를 true||false 값으로 내려줘서 
- false 일 경우 opacity-60 고정 값과 onClick (e)  를 주지 않아서 건드릴 수 없게 만들고 only 오른쪽 함께하기 버튼을 통해 신청할 수 있도록 수정함.
- true 일 경우 onClick(e) 를 통해 클릭 대상만 opacity 100 값으로 변경해주며 , 오른쪽 함께하기 버튼을 통해 select이 가능하도록 할 예정

2022-11-23 04:43 UTC, haileyport requested changes
회의 시작 전이라 간단하게만 남깁니다!!

2022-11-23 04:43 UTC, haileyport commented on client/src/components/UI/organisms/Comments.js
>                  <ViewerCL
props 넘길 때 너무 많으니까 nickname. contents는 data로 묶어서 보내면 좋을 거 같아요~
id도 같이 넘길 수 있을 거 같은데 이건 api 붙여봐야 더 정확하게 알겠네요!

2022-11-23 04:43 UTC, haileyport commented on client/src/components/UI/organisms/Comments.js
>          if (!reply[idx]) {
if문이 너무 많이 걸쳐있어서 코드의 가독성이 떨어진다고 느껴지네요 🥲
회의 시간에 여기 if문 조건 설명 한 번 부탁 드려도 괜찮을까요?

2022-11-23 04:43 UTC, haileyport commented on client/src/components/templates/ArounderWriter.js
> +      <DetailContentsWriter
ArounderViewer.js에서 writer인지 체크해서 삭제/수정 버튼을 띄울 수 있지 않을까요?

2022-11-24 04:26 UTC, seunghw approved these changes
고생하셨습니다~!

2022-11-24 04:26 UTC, haileyport approved these changes
수고하셨습니다~!

2022-11-24 04:26 UTC, merged