✨ Feat: 이미지 처리 로직 구현
codestates-seb/seb40_main_001 pull request #112
Opened 2022-11-22 16:55 UTC by hyeongiii

- 이미지 처리 로직 입니다.

2022-11-23 02:12 UTC, Qone2 reviewed
감사합니다!

제가 보기에는 잘 해주신거 같아요!

2022-11-23 02:12 UTC, Qone2 commented on server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
> +            createdExercise.addImages(images);
반대쪽 연관관계에 add하는 작업은 사실 영속성컨텍스트가 자동으로 해주는 일이라 안해줘도 됩니다. 물론 테스트를 위해 추가 할 수도 있지만요.
그것보다는 image에 exercise를 결정해주는게 필요합니다.

2022-11-23 03:59 UTC, hyeongiii commented on server/.gitignore
> +was-logs/
로그 압축파일이 생성되는 디렉토리입니다!

2022-11-23 04:01 UTC, hyeongiii commented on server/src/main/java/com/ilchinjo/mainproject/domain/image/controller/ImageController.java
> +                                            @RequestHeader(name = "Authorization") Long memberId) throws IOException {
메서드명과 url 매핑 변경하겠습니다!

단일 이미지 첨부 url: /image
다중 이미지 첨부 url: /images

이렇게 바꾸면 혼동이 올까요..?

혹은

단일 이미지 첨부 : /images
다중 이미지 첨부 : /images/multi
이렇게 하는게 더 나을까요??

2022-11-23 05:32 UTC, hyeongiii commented on server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java
> +                                             @RequestHeader(name = "Authorization") Long memberId) {
앗..! 작업을 하다보니 합쳐져서 올라갔는데 PR을 따로 뺄까요??

2022-11-24 02:26 UTC, Qone2 approved these changes
정말 고생 많으셨습니다.
감사합니다!

2022-11-24 02:53 UTC, yujung-Jang submitted a review, later dismissed
확인했습니다! 감사합니다!!

2022-11-24 03:27 UTC, Qone2 requested changes
감사합니다!
한번만 더 수정해주세요

2022-11-24 03:27 UTC, Qone2 commented on server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java
>      private List<Review> reviews = new ArrayList<>();
71번 공백줄은 없는게 보기 좋을거 같습니다.
reviews에도 `@Builder.Default
    @OneToMany(mappedBy = "exercise", cascade = CascadeType.REMOVE)` 추가해주세요!
에러나요ㅠㅠ😅

2022-11-24 03:41 UTC, Qone2 approved these changes
감사합니다!😄

2022-11-24 03:42 UTC, merged