🐛Fix: 마이페이지 버그 수정
codestates-seb/seb40_main_001 pull request #278
Opened 2022-12-03 17:19 UTC by haileyport

상세 내용은 커밋 메세지 확인 부탁드립니다~

2022-12-03 17:46 UTC, seunghw requested changes

2022-12-03 17:46 UTC, seunghw commented on client/src/components/UI/molecules/HistoryCards.js
> +  // eslint-disable-next-line no-unused-vars
이부분 이제 에러안나면 지워주세용

2022-12-03 17:46 UTC, seunghw commented on client/src/components/UI/molecules/HistoryCards.js
> +        console.log('host img');
콘솔 필요없으면 지워주세요!

2022-12-04 03:20 UTC, haileyport commented on client/src/components/UI/molecules/HistoryCards.js
> +  // eslint-disable-next-line no-unused-vars
setMyId 때문에 eslint에러나서 추가되었어용

2022-12-04 03:22 UTC, haileyport commented on client/src/components/UI/molecules/HistoryCards.js
> +        console.log('host img');
콘솔 지웠습니다~

2022-12-04 04:31 UTC, seunghw approved these changes

2022-12-04 04:31 UTC, merged