✨ Feat: 리뷰 POST API
codestates-seb/seb40_main_001 pull request #56
Opened 2022-11-17 07:27 UTC by hyeongiii

- 리뷰 작성 post api 생성

2022-11-17 07:46 UTC, Qone2 reviewed
감사합니다!

2022-11-17 07:46 UTC, Qone2 commented on server/src/main/java/com/ilchinjo/mainproject/domain/review/dto/ReviewPostDto.java
> +    private int privateEvaluation;
\@Range 어노테이션 추가해주면 좋을거 같아요. 아직 validation을 신경 쓸 단계는 아닐지도  모르지만요.

2022-11-17 07:46 UTC, Qone2 commented on server/src/main/java/com/ilchinjo/mainproject/domain/review/repository/ReviewRepository.java
> +     List<Review> findByExercise(Exercise exercise);
find"All"이 없어도 딱히 문제는 없네요?

2022-11-17 07:46 UTC, Qone2 commented on server/src/main/java/com/ilchinjo/mainproject/domain/review/dto/ReviewPostDto.java
> +    private MemberSimpleDto destMember;
그냥 Long destMemberId만 받아도 괜찮지 않을까 생각합니다.

2022-11-17 07:46 UTC, Qone2 commented on server/src/main/java/com/ilchinjo/mainproject/domain/review/service/ReviewServiceImpl.java
> +    }
운동을 찾은 후에 운동종료시간에 대한 검증도 있으면 좋을 것 같습니다!

2022-11-17 07:51 UTC, hyeongiii commented on server/src/main/java/com/ilchinjo/mainproject/domain/review/dto/ReviewPostDto.java
> +    private MemberSimpleDto destMember;
저걸 Long으로 받으면 mapping이 잘 안되더라구요..! 
수동으로 매핑해줄까요..?

2022-11-17 07:52 UTC, hyeongiii commented on server/src/main/java/com/ilchinjo/mainproject/domain/review/repository/ReviewRepository.java
> +     List<Review> findByExercise(Exercise exercise);
네 그런 것 같습니다..!!!

2022-11-17 07:52 UTC, hyeongiii commented on server/src/main/java/com/ilchinjo/mainproject/domain/review/dto/ReviewPostDto.java
> +    private int privateEvaluation;
앗 수정하겠습니다!

2022-11-17 07:56 UTC, Qone2 commented on server/src/main/java/com/ilchinjo/mainproject/domain/review/dto/ReviewPostDto.java
> +    private MemberSimpleDto destMember;
postDto -> review엔티티로의 매핑시 destMemberId는 없어도 괜찮지 않나요?

2022-11-17 08:24 UTC, hyeongiii commented on server/src/main/java/com/ilchinjo/mainproject/domain/review/dto/ReviewPostDto.java
> +    private MemberSimpleDto destMember;
앗 맞아요!!!!!!! 대박!!!!!!!!!

2022-11-17 08:24 UTC, hyeongiii commented on server/src/main/java/com/ilchinjo/mainproject/domain/review/service/ReviewServiceImpl.java
> +    }
이 부분도 수정하겠습니다!

2022-11-17 09:05 UTC, yujung-Jang reviewed
확인했습니다! 수고하셨어요!! 😊

2022-11-17 09:07 UTC, Qone2 requested changes
수고하셨습니다! 감사합니다!

2022-11-17 09:07 UTC, Qone2 commented on server/src/main/java/com/ilchinjo/mainproject/domain/review/service/ReviewServiceImpl.java
> +    }
생각해보니까 되는 경우들을 나열하기 보다 안되는 경우 하나만 나열해도 좋을거 같아요
findByExerciseAndSrcMember로 찾아서 empty가 아니면 안되게 하는거 어떨까요

2022-11-18 04:27 UTC, yujung-Jang approved these changes
확인했습니다! 😊

2022-11-18 04:41 UTC, Qone2 submitted a review, later dismissed
감사합니다!!

2022-11-18 06:19 UTC, Qone2 approved these changes
감사합니다!

2022-11-18 06:19 UTC, merged